### ISSUE TITLE
Linux SteamCMD complaining about failed UTF8 locale

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-srcds#1]
**Symptom**

When SteamCMD runs it complains about failed UTF-8 locale:

```text
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/app/Steam/logs/stderr.txt'
```

**Background**
While not a big deal for this docker image, this same warning is plaguing all of our SRCDS-based Docker images (BlackMesa, CSGO, TF2, etc). It is in these other Docker images that this could become a big deal, as players joining our game servers are likely going to use UTF-8 characters in their screennames:

- Some just want theirs to be unique/interesting: `(｡◕ ∀ ◕｡) ☃`
- Others may do it to intentional mess with things: `\u0001\u0002\u0003\`

Best case scenario would be that server log files have wrongly encoded strings. Worst case scenario, projects like [sourceseer](https://github.com/LacledesLAN/sourceseer) which depend on game server logs in real time has issues and ruins a tournament.

**Task**

It makes sense to fix it in this simple Docker image first; then take that fix to all impacted images.

- [x] Determine the root cause of this complaint and fix it. Once fixed and verified we can work on the same fix in all SRCDS based Docker images.
- [x] Write a test that to verify the issues is no longer occurring, and add to `/dist/linux/ll-tests/steamcmd.sh`. Verify test fails when issue occurs.

**Comment by mattburchett** [comment]
I submitted a PR (#2) hopefully that will fix this. 

Part of the `locales` package is the locales themselves, so when you remove the package, you remove the locales that you generated. 

I was able to find that out by first installing the package and using `dpkg -L` to see what the package contained and confirming that the file existed.

```Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.

root@6f74474b426c:/app# dpkg -L locales | grep en_US
/usr/share/i18n/locales/en_US

root@6f74474b426c:/app# ls -alh /usr/share/i18n/locales/en_US
-rw-r--r-- 1 root root 3.4K May  1  2019 /usr/share/i18n/locales/en_US
```

Then I removed the package and found that the locales were missing: 
```
root@6f74474b426c:/app# apt remove locales
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libc-l10n
Use 'apt autoremove' to remove it.
The following packages will be REMOVED:
  locales
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 16.5 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 8106 files and directories currently installed.)
Removing locales (2.28-10) ...

root@6f74474b426c:/app# ls -alh /usr/share/i18n/locales/en_US
ls: cannot access '/usr/share/i18n/locales/en_US': No such file or directory
```

The PR contains just removing the apt remove for the locales package and that stops the errors that are coming through steamcmd.sh.

**Comment by dudleycodes** [comment]
Awesome @mattburchett 

I updated the tests in commit 65b1b25 - if you would, review it and let me know if there's anything I missed.

Thanks!
